/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSimulatorRouteImport } from './routes/_authenticated/simulator'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicWebhooksWhatsappRouteImport } from './routes/api/public/webhooks/whatsapp'
import { Route as ApiPublicWebhooksTelegramRouteImport } from './routes/api/public/webhooks/telegram'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api/public/webhooks/paystack'
import { Route as ApiPublicHooksRunRemindersRouteImport } from './routes/api/public/hooks/run-reminders'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSimulatorRoute = AuthenticatedSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWebhooksWhatsappRoute =
  ApiPublicWebhooksWhatsappRouteImport.update({
    id: '/api/public/webhooks/whatsapp',
    path: '/api/public/webhooks/whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksTelegramRoute =
  ApiPublicWebhooksTelegramRouteImport.update({
    id: '/api/public/webhooks/telegram',
    path: '/api/public/webhooks/telegram',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRunRemindersRoute =
  ApiPublicHooksRunRemindersRouteImport.update({
    id: '/api/public/hooks/run-reminders',
    path: '/api/public/hooks/run-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/products': typeof AuthenticatedProductsRoute
  '/simulator': typeof AuthenticatedSimulatorRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/api/public/webhooks/telegram': typeof ApiPublicWebhooksTelegramRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/products': typeof AuthenticatedProductsRoute
  '/simulator': typeof AuthenticatedSimulatorRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/api/public/webhooks/telegram': typeof ApiPublicWebhooksTelegramRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/simulator': typeof AuthenticatedSimulatorRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/api/public/webhooks/telegram': typeof ApiPublicWebhooksTelegramRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/products'
    | '/simulator'
    | '/api/public/hooks/run-reminders'
    | '/api/public/webhooks/paystack'
    | '/api/public/webhooks/telegram'
    | '/api/public/webhooks/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/products'
    | '/simulator'
    | '/api/public/hooks/run-reminders'
    | '/api/public/webhooks/paystack'
    | '/api/public/webhooks/telegram'
    | '/api/public/webhooks/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/products'
    | '/_authenticated/simulator'
    | '/api/public/hooks/run-reminders'
    | '/api/public/webhooks/paystack'
    | '/api/public/webhooks/telegram'
    | '/api/public/webhooks/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksRunRemindersRoute: typeof ApiPublicHooksRunRemindersRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
  ApiPublicWebhooksTelegramRoute: typeof ApiPublicWebhooksTelegramRoute
  ApiPublicWebhooksWhatsappRoute: typeof ApiPublicWebhooksWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/simulator': {
      id: '/_authenticated/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof AuthenticatedSimulatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/whatsapp': {
      id: '/api/public/webhooks/whatsapp'
      path: '/api/public/webhooks/whatsapp'
      fullPath: '/api/public/webhooks/whatsapp'
      preLoaderRoute: typeof ApiPublicWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/telegram': {
      id: '/api/public/webhooks/telegram'
      path: '/api/public/webhooks/telegram'
      fullPath: '/api/public/webhooks/telegram'
      preLoaderRoute: typeof ApiPublicWebhooksTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/paystack': {
      id: '/api/public/webhooks/paystack'
      path: '/api/public/webhooks/paystack'
      fullPath: '/api/public/webhooks/paystack'
      preLoaderRoute: typeof ApiPublicWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-reminders': {
      id: '/api/public/hooks/run-reminders'
      path: '/api/public/hooks/run-reminders'
      fullPath: '/api/public/hooks/run-reminders'
      preLoaderRoute: typeof ApiPublicHooksRunRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedSimulatorRoute: typeof AuthenticatedSimulatorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedSimulatorRoute: AuthenticatedSimulatorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksRunRemindersRoute: ApiPublicHooksRunRemindersRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
  ApiPublicWebhooksTelegramRoute: ApiPublicWebhooksTelegramRoute,
  ApiPublicWebhooksWhatsappRoute: ApiPublicWebhooksWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
