/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWebhooksWhatsappRouteImport } from './routes/api/public/webhooks/whatsapp'
import { Route as ApiPublicWebhooksTelegramRouteImport } from './routes/api/public/webhooks/telegram'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api/public/webhooks/paystack'
import { Route as ApiPublicHooksRunRemindersRouteImport } from './routes/api/public/hooks/run-reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksWhatsappRoute =
  ApiPublicWebhooksWhatsappRouteImport.update({
    id: '/api/public/webhooks/whatsapp',
    path: '/api/public/webhooks/whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksTelegramRoute =
  ApiPublicWebhooksTelegramRouteImport.update({
    id: '/api/public/webhooks/telegram',
    path: '/api/public/webhooks/telegram',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRunRemindersRoute =
  ApiPublicHooksRunRemindersRouteImport.update({
    id: '/api/public/hooks/run-reminders',
    path: '/api/public/hooks/run-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/api/public/webhooks/telegram': typeof ApiPublicWebhooksTelegramRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/api/public/webhooks/telegram': typeof ApiPublicWebhooksTelegramRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/api/public/webhooks/telegram': typeof ApiPublicWebhooksTelegramRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/hooks/run-reminders'
    | '/api/public/webhooks/paystack'
    | '/api/public/webhooks/telegram'
    | '/api/public/webhooks/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/hooks/run-reminders'
    | '/api/public/webhooks/paystack'
    | '/api/public/webhooks/telegram'
    | '/api/public/webhooks/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/api/public/hooks/run-reminders'
    | '/api/public/webhooks/paystack'
    | '/api/public/webhooks/telegram'
    | '/api/public/webhooks/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicHooksRunRemindersRoute: typeof ApiPublicHooksRunRemindersRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
  ApiPublicWebhooksTelegramRoute: typeof ApiPublicWebhooksTelegramRoute
  ApiPublicWebhooksWhatsappRoute: typeof ApiPublicWebhooksWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/whatsapp': {
      id: '/api/public/webhooks/whatsapp'
      path: '/api/public/webhooks/whatsapp'
      fullPath: '/api/public/webhooks/whatsapp'
      preLoaderRoute: typeof ApiPublicWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/telegram': {
      id: '/api/public/webhooks/telegram'
      path: '/api/public/webhooks/telegram'
      fullPath: '/api/public/webhooks/telegram'
      preLoaderRoute: typeof ApiPublicWebhooksTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/paystack': {
      id: '/api/public/webhooks/paystack'
      path: '/api/public/webhooks/paystack'
      fullPath: '/api/public/webhooks/paystack'
      preLoaderRoute: typeof ApiPublicWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-reminders': {
      id: '/api/public/hooks/run-reminders'
      path: '/api/public/hooks/run-reminders'
      fullPath: '/api/public/hooks/run-reminders'
      preLoaderRoute: typeof ApiPublicHooksRunRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicHooksRunRemindersRoute: ApiPublicHooksRunRemindersRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
  ApiPublicWebhooksTelegramRoute: ApiPublicWebhooksTelegramRoute,
  ApiPublicWebhooksWhatsappRoute: ApiPublicWebhooksWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
